version: "3"

services:
  web:
    build: .
    restart: on-failure
    command: bash -c "python3 manage.py migrate && python3 autoadmin.py && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
