# Generated by Django 3.2.5 on 2021-08-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20210818_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='activated',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='media/csvs'),
        ),
    ]
