# Generated by Django 3.2.5 on 2021-08-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_alter_document_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='epochs',
            field=models.IntegerField(default=10),
        ),
    ]
