# Generated by Django 3.2.5 on 2021-08-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_document_epochs'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hidden_layers',
            field=models.IntegerField(default=2),
        ),
    ]
